import { motion } from "framer-motion";
import { ShieldCheck } from "lucide-react";

const sections = [
  {
    title: "1. Information We Collect",
    body: "We collect information you provide directly, such as your name, email, phone number, delivery address, and payment details, as well as information generated by your use of the platform, like order history and browsing activity.",
  },
  {
    title: "2. How We Use Your Information",
    body: "We use your information to process orders, provide customer support, personalize your experience, send order updates, and improve our products and services. We do not sell your personal information to third parties.",
  },
  {
    title: "3. Cookies & Tracking",
    body: "We use cookies and similar technologies to remember your preferences, keep you logged in, and understand how you use our platform so we can improve it over time. You can control cookies through your browser settings.",
  },
  {
    title: "4. Sharing Your Information",
    body: "We share information only with trusted service providers who help us operate — such as payment processors and delivery partners — and only to the extent necessary to fulfil your order.",
  },
  {
    title: "5. Data Security",
    body: "We use industry-standard security measures, including encrypted checkout, to protect your personal and payment information. No method of transmission over the internet is 100% secure, but we work continuously to safeguard your data.",
  },
  {
    title: "6. Your Rights",
    body: "You can access, update, or request deletion of your personal information at any time from your Account settings, or by contacting our support team directly.",
  },
  {
    title: "7. Children's Privacy",
    body: "Quenchly is not intended for use by anyone under 18. We do not knowingly collect personal information from children.",
  },
  {
    title: "8. Changes to This Policy",
    body: "We may update this Privacy Policy periodically. We'll notify you of significant changes by posting the updated policy on this page with a new effective date.",
  },
  {
    title: "9. Contact Us",
    body: "For any questions about this Privacy Policy or how your data is handled, contact us at hello@quenchly.com.",
  },
];

export default function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="mb-10 text-center"
      >
        <span className="grid place-items-center w-12 h-12 rounded-xl2 bg-primary-50 text-primary-600 mx-auto mb-4">
          <ShieldCheck size={22} />
        </span>
        <h1 className="text-3xl sm:text-4xl font-bold text-ink">
          Privacy Policy
        </h1>
        <p className="text-ink/50 text-sm mt-2">Last updated: July 1, 2026</p>
      </motion.div>

      <div className="bg-white rounded-xl4 shadow-softer p-6 sm:p-9 space-y-7">
        {sections.map((section, i) => (
          <motion.div
            key={section.title}
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.3 }}
            transition={{ duration: 0.35, delay: Math.min(i * 0.04, 0.3) }}
          >
            <h2 className="text-base sm:text-lg font-bold text-ink mb-2">
              {section.title}
            </h2>
            <p className="text-sm text-ink/60 leading-relaxed">{section.body}</p>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
